/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fernando Gonzalez
 */
public class jfrmCalculadoraNueva extends javax.swing.JFrame {

    /**
     * Creates new form jfrmCalculadoraNueva
     */
    private String entrada="";
    private double numero1, numero2;
    private String operador;
    private void calcularParcial() {
    if (!entrada.equals("") && operador != null) {
        double valor = Double.parseDouble(entrada);

        if (operador.equals("+")) {
            numero1 += valor;
        } else if (operador.equals("-")) {
            numero1 -= valor;
        } else if (operador.equals("*")) {
            numero1 *= valor;
        } else if (operador.equals("/")) {
            numero1 /= valor;
        }

        entrada = String.valueOf(numero1);
        jbxtCantidad.setText(entrada);
    }
}
    public jfrmCalculadoraNueva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn1 = new javax.swing.JButton();
        jbtnQuitar = new javax.swing.JButton();
        jbtnMas = new javax.swing.JButton();
        jbxtCantidad = new javax.swing.JTextField();
        jbtnIgual = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtnResta = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtnDivi = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtnBorrar = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtnPunto = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnPorcentaje = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtnRaizCuadrada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtnQuitar.setText("C");
        jbtnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuitarActionPerformed(evt);
            }
        });

        jbtnMas.setText("+");
        jbtnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMasActionPerformed(evt);
            }
        });

        jbxtCantidad.setEnabled(false);

        jbtnIgual.setText("=");
        jbtnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIgualActionPerformed(evt);
            }
        });

        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtnResta.setText("-");
        jbtnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRestaActionPerformed(evt);
            }
        });

        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtnMulti.setText("*");
        jbtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiActionPerformed(evt);
            }
        });

        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtnDivi.setText("/");
        jbtnDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDiviActionPerformed(evt);
            }
        });

        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtnBorrar.setText("AC");
        jbtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBorrarActionPerformed(evt);
            }
        });

        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtnPunto.setText(".");
        jbtnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPuntoActionPerformed(evt);
            }
        });

        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnPorcentaje.setText("%");
        jbtnPorcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPorcentajeActionPerformed(evt);
            }
        });

        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtnRaizCuadrada.setText("√");
        jbtnRaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRaizCuadradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnIgual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnMas))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jbtnDivi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtnPorcentaje)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbtnQuitar))
                                .addComponent(jbtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnMulti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnRaizCuadrada))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnResta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jbxtCantidad))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jbxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn7)
                    .addComponent(jbtn8)
                    .addComponent(jbtn9)
                    .addComponent(jbtnBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn4)
                    .addComponent(jbtn5)
                    .addComponent(jbtn6)
                    .addComponent(jbtnDivi)
                    .addComponent(jbtnQuitar)
                    .addComponent(jbtnPorcentaje))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn1)
                    .addComponent(jbtn2)
                    .addComponent(jbtn3)
                    .addComponent(jbtnMulti)
                    .addComponent(jbtnRaizCuadrada))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn0)
                    .addComponent(jbtnIgual)
                    .addComponent(jbtnMas)
                    .addComponent(jbtnResta)
                    .addComponent(jbtnPunto))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 1;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuitarActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")) {
            entrada = entrada.substring(0, entrada.length() - 1);

            if (entrada.equals("")) {
                jbxtCantidad.setText("0");
            } else {
                jbxtCantidad.setText(entrada);
            }
        }
    }//GEN-LAST:event_jbtnQuitarActionPerformed

    private void jbtnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMasActionPerformed
        // TODO add your handling code here:
        calcularParcial();
        numero1 = Double.parseDouble(entrada);
        entrada="";
        operador="+";
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnMasActionPerformed

    private void jbtnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIgualActionPerformed
        // TODO add your handling code here:
        double resultado;
        numero2 = Double.parseDouble(entrada);
        jbxtCantidad.setText("");
        entrada="";
        if(operador.equals("*")){
            resultado=numero1*numero2;
            entrada=String.valueOf(resultado);
            jbxtCantidad.setText(entrada);
        }else if(operador.equals("-")){
            resultado=numero1-numero2;
            entrada=String.valueOf(resultado);
            jbxtCantidad.setText(entrada);
        }else if(operador.equals("+")){
            resultado=numero1+numero2;
            entrada=String.valueOf(resultado);
            jbxtCantidad.setText(entrada);
        }else if(operador.equals("/")){
            resultado=numero1/numero2;
            entrada=String.valueOf(resultado);
            jbxtCantidad.setText(entrada);
        }

        operador = null;   // 👈 AGREGA ESTO
        numero1 = 0;
    }//GEN-LAST:event_jbtnIgualActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 7;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 0;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 8;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestaActionPerformed
        // TODO add your handling code here:
        calcularParcial();
        numero1 = Double.parseDouble(entrada);
        entrada="";
        operador="-";
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnRestaActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 9;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        // TODO add your handling code here:
        calcularParcial();
        numero1 = Double.parseDouble(entrada);
        entrada="";
        operador="*";
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 4;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtnDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDiviActionPerformed
        // TODO add your handling code here:
        calcularParcial();
        numero1 = Double.parseDouble(entrada);
        entrada="";
        operador="/";
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnDiviActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 5;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBorrarActionPerformed
        // TODO add your handling code here:
        entrada="";
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnBorrarActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 6;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuntoActionPerformed
        // TODO add your handling code here:
        if (!entrada.contains(".")) {
            entrada = entrada + ".";
            jbxtCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtnPuntoActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 3;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnPorcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPorcentajeActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")) {
            double valor = Double.parseDouble(entrada);
            valor = valor / 100;
            entrada = String.valueOf(valor);
            jbxtCantidad.setText(entrada);
        }
    }//GEN-LAST:event_jbtnPorcentajeActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        entrada= entrada + 2;
        jbxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtnRaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRaizCuadradaActionPerformed
        // TODO add your handling code here:
        if (!entrada.equals("")) {
            double valor = Double.parseDouble(entrada);

            if (valor >= 0) {
                double resultado = Math.sqrt(valor);
                entrada = String.valueOf(resultado);
                jbxtCantidad.setText(entrada);
            } else {
                jbxtCantidad.setText("Error");
                entrada = "";
            }
        }
    }//GEN-LAST:event_jbtnRaizCuadradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalculadoraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalculadoraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalculadoraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalculadoraNueva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalculadoraNueva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnBorrar;
    private javax.swing.JButton jbtnDivi;
    private javax.swing.JButton jbtnIgual;
    private javax.swing.JButton jbtnMas;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnPorcentaje;
    private javax.swing.JButton jbtnPunto;
    private javax.swing.JButton jbtnQuitar;
    private javax.swing.JButton jbtnRaizCuadrada;
    private javax.swing.JButton jbtnResta;
    private javax.swing.JTextField jbxtCantidad;
    // End of variables declaration//GEN-END:variables
}
